### ISSUE TITLE
Error: Container action is only supported on Linux

### ISSUE THREAD

**Issue by vivekfe** [cpina/push-to-another-repository-deploy-keys-example#1]
Hi, I am trying to deploy my static site through a dedicated repository to another repo's main branch but it fails. 

**Current repository:**  https://github.com/vivekfe/iostories
**Destination repository:**  https://github.com/vivekfe/vivekfe.github.io

Has anyone faced this issue before ? Below is my action workflow file.

```
name: ci 
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: |
          pip install pip
          pip install setuptools
          pip install wheel 
          pip install -U mkdocs-material 
          pip install pandas 
          pip install -U mkdocs-awesome-pages-plugin
          pip install -U git+https://github.com/frankkopp/mkdocs-redirects.git 
          pip install -U mkdocs-git-revision-date-localized-plugin
          pip install -U mkdocs-encryptcontent-plugin 
          pip install -U mkdocs-exclude 
          pip install -U markdown-captions
          pip install -U markdown-customblocks
          pip install -U git+https://github.com/vuquangtrong/cell_row_span.git

      - run: mkdocs build
      - run: mkdocs gh-deploy --force
      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        with:
          source-directory: 'site'
          destination-github-username: 'vivekfe'
          destination-repository-name: 'vivekfe.github.io'
          user-email: carles3@pina.cat
          target-branch: main

```
